# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sat Apr 21 16:01:29 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 619)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.whiteTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.whiteTab.sizePolicy().hasHeightForWidth())
        self.whiteTab.setSizePolicy(sizePolicy)
        self.whiteTab.setObjectName("whiteTab")
        self.verticalLayout = QtGui.QVBoxLayout(self.whiteTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.whiteList = QtGui.QListView(self.whiteTab)
        self.whiteList.setObjectName("whiteList")
        self.verticalLayout.addWidget(self.whiteList)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.addWhiteBtn = QtGui.QPushButton(self.whiteTab)
        self.addWhiteBtn.setObjectName("addWhiteBtn")
        self.horizontalLayout_3.addWidget(self.addWhiteBtn)
        self.removeWhiteBtn = QtGui.QPushButton(self.whiteTab)
        self.removeWhiteBtn.setObjectName("removeWhiteBtn")
        self.horizontalLayout_3.addWidget(self.removeWhiteBtn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.whiteTab, "")
        self.blackTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blackTab.sizePolicy().hasHeightForWidth())
        self.blackTab.setSizePolicy(sizePolicy)
        self.blackTab.setObjectName("blackTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.blackTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.blackList = QtGui.QTableView(self.blackTab)
        self.blackList.setObjectName("blackList")
        self.verticalLayout_2.addWidget(self.blackList)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.addBlackBtn = QtGui.QPushButton(self.blackTab)
        self.addBlackBtn.setObjectName("addBlackBtn")
        self.horizontalLayout_2.addWidget(self.addBlackBtn)
        self.removeBlackBtn = QtGui.QPushButton(self.blackTab)
        self.removeBlackBtn.setObjectName("removeBlackBtn")
        self.horizontalLayout_2.addWidget(self.removeBlackBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.blackTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionPrintPreview = QtGui.QAction(MainWindow)
        self.actionPrintPreview.setObjectName("actionPrintPreview")
        self.actionExportPDF = QtGui.QAction(MainWindow)
        self.actionExportPDF.setObjectName("actionExportPDF")
        self.actionExportFO = QtGui.QAction(MainWindow)
        self.actionExportFO.setObjectName("actionExportFO")
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSaveAs = QtGui.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrintPreview)
        self.menuFile.addAction(self.actionExportPDF)
        self.menuFile.addAction(self.actionExportFO)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Cards Against Sanity", None, QtGui.QApplication.UnicodeUTF8))
        self.addWhiteBtn.setText(QtGui.QApplication.translate("MainWindow", "Add Card", None, QtGui.QApplication.UnicodeUTF8))
        self.removeWhiteBtn.setText(QtGui.QApplication.translate("MainWindow", "Remove Card", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.whiteTab), QtGui.QApplication.translate("MainWindow", "White Cards", None, QtGui.QApplication.UnicodeUTF8))
        self.addBlackBtn.setText(QtGui.QApplication.translate("MainWindow", "Add Card", None, QtGui.QApplication.UnicodeUTF8))
        self.removeBlackBtn.setText(QtGui.QApplication.translate("MainWindow", "Remove Card", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blackTab), QtGui.QApplication.translate("MainWindow", "Black Cards", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About Cards Against Sanity", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPrintPreview.setText(QtGui.QApplication.translate("MainWindow", "Print Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportPDF.setText(QtGui.QApplication.translate("MainWindow", "Export to PDF", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExportFO.setText(QtGui.QApplication.translate("MainWindow", "Export to XSL-FO", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("MainWindow", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("MainWindow", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))

